FROM snapchange_base_fuzzer

# Copy the fuzzer into the container
# Build a basic application just to pre-build all of the dependencies
WORKDIR /fuzzer
COPY --chown=${user}:${user} Cargo.toml /fuzzer
COPY --chown=${user}:${user} build.rs   /fuzzer
COPY --chown=${user}:${user} snapshot/fuzzvm.qemuregs  /fuzzer/snapshot/fuzzvm.qemuregs
COPY --chown=${user}:${user} snapshot/vm.log /fuzzer/snapshot/vm.log
RUN mkdir /fuzzer/src && echo 'fn test() { println!("NULL test"); }' > /fuzzer/src/lib.rs

# Pre-build the fuzzer and snapchange to cache
RUN cargo add snapchange --path /snapchange
RUN cargo build -r

RUN rm /fuzzer/src/lib.rs

# Re-add the src folder to only add modified files back to the image
# When developing the fuzzer, the builds should start here to help speed up dev time
COPY --chown=${user}:${user} src /fuzzer/src

# Start fuzzing
ENTRYPOINT ["cargo", "run", "-r", "--"]
