# fill in correct name of the image!
ARG BASEIMG=harness
FROM $BASEIMG as base

#### snapchange snapshot container ####
FROM ghcr.io/awslabs/snapchange

# copy whole root filesystem from build environment to this container layer
# SNAPSHOT_INPUT is the location that the snapshotting script will create.
COPY --from=base / "$SNAPSHOT_INPUT"

# set the path to the target within the root filesystem of the build environment
ENV SNAPSHOT_ENTRYPOINT=/opt/...
# optionally: set the working directory of the target
# ENV SNAPSHOT_ENTRYPOINT_CWD="/opt/"
