FROM snapchange_example1:target as target

RUN apk add --no-cache --initramfs-diskless-boot python3 gdb curl tar build-base perf musl-dbg

FROM snapchange_snapshot
COPY --from=target / "$SNAPSHOT_INPUT"

ENV SNAPSHOT_ENTRYPOINT=/opt/example1
