[package]
name = "gather_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snapchange = { version = "0.1.0", path = "../.." }
tokio = { version = "1.26.0", features = ["full"] }
toml = "0.7.3"
